apiVersion: v1
kind: Secret
metadata:
  name: grafana
type: Opaque
data:
  awscreds: {{.AWS_CREDENTIALS}}
  adminpassword: {{.GRAFANA_ADMIN_PASSWD}}
---
apiVersion: v1
kind: Secret
metadata:
  name: grafana-auth
type: Opaque
data:
  ca.crt: {{.CA_CRT}}